2023-05-11 00:01:26,837 - telegram.ext.Application - INFO - Application started
2023-05-11 00:01:44,258 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/andre/.local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/home/andre/.local/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/mnt/c/github/alt-text-gpt/main.py", line 52, in image
    obj.download()
AttributeError: 'File' object has no attribute 'download'
2023-05-11 17:40:32,772 - telegram.ext.Application - INFO - Application started
2023-05-11 17:43:26,966 - telegram.ext.Application - INFO - Application started
